### ISSUE TITLE
Add recipe for indivious

### ISSUE THREAD

**Issue by funkypenguin** [geek-cookbook/geek-cookbook#107]
As suggested in Discord - https://github.com/omarroth/invidious

**Comment by SuperSandro2000** [comment]
I suggest using my PR https://github.com/omarroth/invidious/pull/1211/files as a base. It removes the dependency on a custom postgres image which is not required.

**Comment by funkypenguin** [comment]
Docker-compose is at https://github.com/iv-org/invidious/blob/master/docker-compose.yml

**Comment by funkypenguin** [comment]
Not mouldy, mould-bot!

**Comment by funkypenguin** [comment]
not mouldy, bot!

**Comment by funkypenguin** [comment]
Not mouldy, silly bot!

**Comment by funkypenguin** [comment]
Done!
