### ISSUE TITLE
[bug report] recipe-autopirate-toc has broken link for NZBGet and SABnzbd

### ISSUE THREAD

**Issue by dajeffers** [geek-cookbook/geek-cookbook#183]
# Waiter! There's a bug in my recipe! 🐛

##  ‼️ Current Behavior
Clicking "NZBGet" or "SABnzbd" in your Autopirate table of contents 404s.

## ✅ Expected behavior
No 404s.

## 👯‍♂️ Steps to reproduce
Go [here](https://geek-cookbook.funkypenguin.co.nz/recipes/autopirate/#assemble-more-tools) and click "NZBGet" or "SABnzbd".

## 📖 Context and logs
[File in question](https://github.com/geek-cookbook/geek-cookbook/blob/master/_snippets/recipe-autopirate-toc.md).

## 💡Possible Solutions 
This is due to recipe-autopirate-toc.md pointing to `https://geek-cookbook.funkypenguin.co.nz/recipes/autopirate/nzbget.md` instead of `https://geek-cookbook.funkypenguin.co.nz/recipes/autopirate/nzbget` (and likewise for SABnzbd).

**Comment by funkypenguin** [comment]
Nice catch, thanks @dajeffers!
