### ISSUE TITLE
[bug report] Traefikv2 Not functional

### ISSUE THREAD

**Issue by Bencey** [geek-cookbook/geek-cookbook#206]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

Currently having issues where the traefikv2 recipe on the cookbook does not work as expected

### 2️⃣ Expected Behaviour

Users should be able to access the dashboard when service is deployed

### 3️⃣ Actual Behaviour

When FQDN is accessed the page will time out

### 4️⃣ Steps to Reproduce

1. Deploy Traefik
2. Attempt to access dashboard

### 5️⃣ Possible solutions

Working on a solution

### 6️⃣ Relevant Information

Issue reported to me by a discord user. I am able to reproduce

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [X] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [X] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Not mouldy, silly bot!

**Comment by Bencey** [comment]
Issue was resolved in #207
