### ISSUE TITLE
[bug report] Fix pgdump env variables in Paperless Ng recipe

### ISSUE THREAD

**Issue by dskaggs** [geek-cookbook/geek-cookbook#211]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

@neographophobic has identified an issue with the environment variables for the pgbackup service in the Paperless Ng recipe. This has been fixed in the premix repo but the recipe page here needs to be updated to reflect the new yaml config.

### 2️⃣ Expected Behaviour

Pg-backup service should successfully create a backup of the PostgreSQL database used by Paperless

### 3️⃣ Actual Behaviour

Backup is erroring out and not completing successfully.

### 4️⃣ Steps to Reproduce

Deploy recipe. Notice errors in logs when pg-backup service attempts to dump the PostgreSQL database.

### 5️⃣ Possible solutions

@neographophobic Has those answers :)

### 💬 Your Discord username

TechHermitD#1436

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [ ] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [ ] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by neographophobic** [comment]
Happy to make the update as requested in #210. The comment their asks to "update the recipe page on the public repo". Can you point me in the right direction for where to find that? The only file I have found is https://github.com/geek-cookbook/geek-cookbook/blob/master/manuscript/recipes/paperless-ng.md, which is what #210 updated.

**Comment by dskaggs** [comment]
Ugh...sorry. Ignore me. I got confused on which repo your PR was for and thought you fixed this in the premix. So I was thinking that the public repo (this one) needed to be updated to match your fix in premix. However (obviously now), I was exactly backwards.

I'll take your fixes here to the recipe page in the public repo and sync the recipe in the premix repo to match.

Thanks again for the fix!
