### ISSUE TITLE
[bug report] topolvm

### ISSUE THREAD

**Issue by biancarosa** [geek-cookbook/geek-cookbook#251]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

Applying the configuration for TopoLVM described in https://geek-cookbook.funkypenguin.co.nz/kubernetes/persistence/topolvm

### 2️⃣ Expected Behaviour

I expected TopoLVM examples work right off the bat

### 3️⃣ Actual Behaviour

- Config gets updated.
- It fails because it doesn't find the `./topolvm-system`  folder
- By fixing that, it fails by not finding the `topo-lvm` namespace

### 4️⃣ Steps to Reproduce

1. Commit and push the example yamls on the repo
2. Waiting for flux reconciliation

### 5️⃣ Possible solutions

The namespace being used for the topolvm configuration + the folder referenced by the kustomization are not appending `--system`.

Maybe we can add `--system` in the folder name & the namespace on the configmap file. Maybe we can get rid of `--system` in the folder name, but add in the namespaces for the configmap file.

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [ ] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [X] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Thanks @biancarosa! You're right, there are some errors here. Did you plan to submit a PR (no pressure, just want to avoid double-work if you've already got something underway) to fix?

Cheers!
D

**Comment by biancarosa** [comment]
I planned to submit a PR, yes! I'm just a bit concerned because I couldn't get it quite working on digital ocean yet - mostly because I still need to understand how to create a volume there. I can fix the namespaces tho, would that be okay?

**Comment by funkypenguin** [comment]
Sorry to take so long to respond here! I've corrected the error :)
