### ISSUE TITLE
[bug report] MetalLB needs updating 

### ISSUE THREAD

**Issue by MegaShinySnivy** [geek-cookbook/geek-cookbook#254]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

As of this morning, the MetalLB v2 chart has been taken offline. This means that the load balancer recipe for k8s is now defunct and will not work properly for those who do not already have the chart installed. This requires a version bump to 4.X along with instructions on configuration.

### 2️⃣ Expected Behaviour

A MetalLB v4 configuration exists on the geek-cookbook site that I can drag into my own lab

### 3️⃣ Actual Behaviour

The current examples point at v2, which no longer exists, meaning that attempting to pull the aforementioned chart just ends up in a loop of invalid chart reference: failed to get chart version for remote reference: no 'metallb' chart with version matching '2.x' found. 

### 4️⃣ Steps to Reproduce

1. Set up a blank k3s cluster
2. Go to the Essentials/Load Balancer/MetalLB page on the geek cookbook website
3. Attempt to go through the instructions for deploying MetalLB
4. Watch the helmrelease object fail to deploy as the chart doesn't exist anymore 

### 5️⃣ Possible solutions

The instructions need updating to v4, which now uses CRDs for management.

### 💬 Your Discord username

MegaShinySnivy#9000

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [X] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [ ] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Resolved in https://github.com/geek-cookbook/geek-cookbook/commit/f4285d860aba91b8a1014b613f0993e3894cf355 :)
