### ISSUE TITLE
Premix repo not using the native MetalLb helmrelease 

### ISSUE THREAD

**Issue by dskaggs** [geek-cookbook/geek-cookbook#268]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

The premix repo is still using the BitNami HelmRelease for MetalLB unlike the public cookbook site.

### 2️⃣ Expected Behaviour

Ansible roles generate helmrelease files consistent with the public cookbook site.

### 3️⃣ Actual Behaviour

Bitnami helmrelease is still generated

### 4️⃣ Steps to Reproduce

1. Run the Ansible deploy role with kubernetes node configuration
2. Observe no metallb helmrelease yaml file is created

### 💬 Your Discord username

TechHermitD

### 💍 Engagement

- [ ] Test the changes after a preview deploy and provide feedback
- [ ] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [ ] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Fixed (by @dskaggs ) in https://github.com/funkypenguin/geek-cookbook-premix/pull/210
