### ISSUE TITLE
Turtle coin address goes off screen

### ISSUE THREAD

**Issue by Bencey** [geek-cookbook/geek-cookbook#30]
![capture](https://user-images.githubusercontent.com/33912370/41208923-cb4edd26-6d7b-11e8-9913-95a0cfa740cf.PNG)

**Comment by Bencey** [comment]
Link to recipe: https://github.com/funkypenguin/geek-cookbook/blob/master/manuscript/recipies/turtle-pool.md

**Comment by funkypenguin** [comment]
I'd suggest that this be replaced with a link to the website, rather than trying to deal with the text wrapping issue :)

**Comment by Bencey** [comment]
Is it possible to get someones wallet via the website?

**Comment by funkypenguin** [comment]
What I mean is, we could just replace the turtlecoin address portion with a link to https://geek-cookbook.funkypenguin.co.nz/support/

**Comment by funkypenguin** [comment]
I.e., something like this:

sed 's/TRTLv123123121212/https:\/\/geek-cookbook.funkypenguin.co.nz\/support\/'. Since the ebook may be read on devices without internet access, we need to make it easy for reader to send TRTL, rather than having to re-type a TRTL address :)

**Comment by Bencey** [comment]
TRTL wallet no longer is in the donate option
