### ISSUE TITLE
[suggestion] I want to add a dark mode button

### ISSUE THREAD

**Issue by VaibhavSharma24** [geek-cookbook/geek-cookbook#300]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue) / [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this suggestion

### 🤕 What's not right?

As i went through the website i noticed that it looks very fleshy if you visit the site in the dark space or in night.

### 🤯 Here's my idea!

so I want to add a dark mode theme button which will enhance the user experience.

### 🤔 On the other hand..

An alternative to this could be dimming the brightness of the screen but it does not solve the problem

### 🤩 But will it fly?

By clicking the button user can make the website change into dark mode

### 💬 Your Discord username

vaibhavpp

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [X] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [X] Submit a PR for a first-cut myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Maybe I need to make it more obvious, but will this do what you're after? :)

<img width="417" alt="How I do  awesome selfhosted  |・∀・ 2023-09-29 11-21-20" src="https://github.com/geek-cookbook/geek-cookbook/assets/1524686/d72f277f-f4ca-43da-95bb-9dd366478c3e">

**Comment by VaibhavSharma24** [comment]
Yes  !
