### ISSUE TITLE
Traefik forward-auth

### ISSUE THREAD

**Issue by stephanrenggli** [geek-cookbook/geek-cookbook#52]
I was looking at your traefik forward-auth recepie as it's one of the simpler ways to implement forward-auth, especially because you can use docker labels.

Do you know of any way to exclude certain paths using this method? Sonarr/Radarr/Lidarr for example rely on /api and /feed (calendar) being accessible without external authentication (api key is used).

I was looking at traefik v2.0 documentation, as it seems the new version will improve authentication and other middleware. However I wasn't able to find anything that would allow for this specific usecase.

If you have interest in looking at authentication again, this project could be interesting: https://github.com/travisghansen/external-auth-server

Thanks for the great resources!

**Comment by funkypenguin** [comment]
Sorry about the delay here! Looks like selective authentication based on paths is now supported in the latest upstream: https://github.com/thomseddon/traefik-forward-auth#configuration
