### ISSUE TITLE
typo in traefik-forward-auth/keycloak recipe

### ISSUE THREAD

**Issue by tlc-sundown** [geek-cookbook/geek-cookbook#74]
In the [Setup environment](https://github.com/funkypenguin/geek-cookbook/blob/master/manuscript/ha-docker-swarm/traefik-forward-auth/keycloak.md#setup-environment) section the following line is missing an 's'
old:
```
COOKIE_DOMAIN=<the root FQDN of your domain>
```
new:
```
COOKIE_DOMAINS=<the root FQDN of your domain>
```

**Comment by SuperSandro2000** [comment]
Depends probably on which fork you are using.

**Comment by funkypenguin** [comment]
The latest upstream is using `COOKIE_DOMAIN` - I'll update the recipe shortly to be sure this all works (no need for my forked image anymore)

**Comment by funkypenguin** [comment]
(upstream is https://github.com/thomseddon/traefik-forward-auth)
