### ISSUE TITLE
Traefik Docker Compose version

### ISSUE THREAD

**Issue by pieman3000** [geek-cookbook/geek-cookbook#75]
Docker Compose for traefik-app.yml (https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik/) needs updating to version 3.2 to avoid error message 'services.traefik.ports.0 must be a string or number'

https://github.com/moby/moby/issues/32202

**Comment by Bencey** [comment]
Made a PR https://github.com/geek-cookbook/geek-cookbook/pull/118 - Thanks
