### ISSUE TITLE
Explain to readers how to use the Discord server

### ISSUE THREAD

**Issue by funkypenguin** [geek-cookbook/geek-cookbook#85]
As @dskaggs pointed out, theres's no "README" for the Discord server, so some users may be unaware of conventions/features.

This issue tracks the addition of a Discord README page to the cookbook, as well as a bot command to trigger a link (`!readme` ?)

**Comment by Bencey** [comment]
Hmmm

**Comment by Bencey** [comment]
Added- https://geek-cookbook.funkypenguin.co.nz/discord/
